
cmake_minimum_required(VERSION 3.11.4)
project (impcheck_modules)

add_definitions("-std=gnu99 -Wall -Wextra -Werror -pedantic-errors -flto -g") 
if(IMPCHECK_WRITE_DIRECTIVES)
    add_definitions("-DIMPCHECK_WRITE_DIRECTIVES=${IMPCHECK_WRITE_DIRECTIVES}")
endif()
if(IMPCHECK_PLRAT)
    add_definitions("-DIMPCHECK_PLRAT=${IMPCHECK_PLRAT}")
endif()
if(IMPCHECK_FLUSH_ALWAYS)
    add_definitions("-DIMPCHECK_FLUSH_ALWAYS=${IMPCHECK_FLUSH_ALWAYS}")
endif()

add_executable(impcheck_parse
    src/trusted/hash.c 
    src/trusted/secret.c 
    src/trusted/siphash.c 
    src/trusted/trusted_parser.c 
    src/trusted/trusted_utils.c 
    src/trusted/vectors.c 
    src/writer.c 
    src/trusted/main_parse.c)

add_executable(impcheck_check 
    src/trusted/confirm.c 
    src/trusted/hash.c 
    src/trusted/lrat_check.c 
    src/trusted/secret.c 
    src/trusted/siphash.c 
    src/trusted/trusted_checker.c 
    src/trusted/top_check.c 
    src/trusted/trusted_utils.c 
    src/trusted/vectors.c 
    src/writer.c
    src/trusted/main_check.c 
    src/trusted/plrat_utils.c)

add_executable(impcheck_confirm
    src/trusted/confirm.c 
    src/trusted/hash.c 
    src/trusted/secret.c 
    src/trusted/siphash.c 
    src/trusted/trusted_parser.c 
    src/trusted/trusted_utils.c 
    src/trusted/clause_flat.c 
    src/trusted/vectors.c 
    src/writer.c 
    src/trusted/main_confirm.c
    src/trusted/heap.c)

add_executable(plrat_first_pass 
    src/trusted/trusted_utils.c 
    src/trusted/top_check.c 
    src/trusted/secret.c 
    src/trusted/confirm.c
    src/writer.c 
    src/trusted/vectors.c 
    src/trusted/hash.c 
    src/trusted/siphash.c 
    src/trusted/siphash_cls.c
    src/trusted/lrat_check.c  
    src/trusted/plrat_utils.c 
    src/trusted/plrat_checker.c 
    src/trusted/plrat_importer.c 
    src/trusted/merge_buffer.c
    src/trusted/clause_flat.c 
    src/trusted/main_plrat_first.c 
    src/trusted/plrat_file_reader.c
    src/trusted/commutative_sig.c
    src/trusted/heap.c)
    

add_executable(plrat_reroute
    src/trusted/main_plrat_reroute.c 
    src/trusted/import_merger.c 
    src/trusted/plrat_reroute.c
    src/trusted/trusted_utils.c
    src/trusted/plrat_utils.c 
    src/trusted/siphash_cls.c 
    src/trusted/siphash.c 
    src/trusted/lrat_check.c 
    src/writer.c 
    src/trusted/hash.c 
    src/trusted/secret.c 
    src/trusted/plrat_file_reader.c
    src/trusted/vectors.c
    src/trusted/commutative_sig.c)

    add_executable(plrat_rebuild
    src/trusted/main_plrat_rebuild_clauses.c 
    src/trusted/import_merger.c 
    src/trusted/plrat_rebuild.c
    src/trusted/trusted_utils.c
    src/trusted/plrat_utils.c 
    src/trusted/siphash_cls.c
    src/trusted/siphash.c 
    src/trusted/lrat_check.c
    src/writer.c 
    src/trusted/hash.c 
    src/trusted/secret.c 
    src/trusted/plrat_file_reader.c
    src/trusted/vectors.c
    src/trusted/commutative_sig.c)

add_executable(plrat_last_pass
    src/trusted/import_merger.c 
    src/trusted/trusted_utils.c 
    src/trusted/plrat_utils.c 
    src/trusted/plrat_finder.c 
    src/writer.c 
    src/trusted/main_plrat_last.c 
    src/trusted/vectors.c 
    src/trusted/hash.c 
    src/trusted/secret.c 
    src/trusted/siphash_cls.c
    src/trusted/siphash.c 
    src/trusted/lrat_check.c
    src/trusted/plrat_file_reader.c
    src/trusted/commutative_sig.c)
    
# Link against math library
target_link_libraries(plrat_first_pass m)
target_link_libraries(plrat_rebuild m)
target_link_libraries(plrat_reroute m)
target_link_libraries(plrat_last_pass m)

add_executable(test_hash 
    src/trusted/trusted_utils.c 
    src/trusted/hash.c 
    src/writer.c 
    test/test.c
    test/test_hash.c)

add_executable(test_full 
    src/trusted/trusted_utils.c 
    src/writer.c 
    test/test.c 
    src/trusted/vectors.c
    test/test_full.c)

add_executable(test_flat_clause 
    src/trusted/trusted_utils.c 
    src/trusted/clause_flat.c 
    test/test.c 
    test/test_clause_flat.c)

add_executable(test_heap 
    src/trusted/trusted_utils.c 
    src/trusted/clause_flat.c 
    src/trusted/heap.c 
    test/test.c 
    test/test_heap.c)

add_executable(test_plrat_importer
    src/trusted/trusted_utils.c 
    src/trusted/clause_flat.c 
    src/trusted/heap.c 
    src/trusted/plrat_utils.c 
    src/trusted/commutative_sig.c
    src/trusted/vectors.c
    src/trusted/secret.c
    src/trusted/plrat_importer.c
    src/trusted/merge_buffer.c
    test/test.c
    test/test_plrat_importer.c)
target_compile_definitions(test_plrat_importer PRIVATE UNIT_TEST)

add_executable(test_plrat_file_reader
    src/trusted/trusted_utils.c 
    src/trusted/plrat_file_reader.c
    test/test.c
    test/test_plrat_file_reader.c)

add_executable(test_merge_buffer
    src/trusted/trusted_utils.c 
    src/trusted/clause_flat.c 
    src/trusted/merge_buffer.c 
    test/test.c 
    test/test_merge_buffer.c)

add_executable(plrat_proxy_to_txt
    src/trusted/trusted_utils.c
    src/trusted/clause_flat.c
    src/trusted/vectors.c
    tools/plrat_proxy_to_txt.c)

add_executable(plrat_proxy_check_hash
    src/trusted/trusted_utils.c
    src/trusted/clause_flat.c
    src/trusted/commutative_sig.c
    src/trusted/vectors.c
    src/trusted/secret.c
    tools/plrat_proxy_check_hash.c)
